apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-jmvo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-jmvo
    app.kubernetes.io/part-of: cin4s-839-0076-app
  name: devfile-sample-jmvo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-jmvo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-jmvo
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0076-tenant/cin4s-839-0076-app/devfile-sample-jmvo@sha256:714083da548dc1194ac112b4b6276d311ee3eed230481d3b636a7801bc749d28
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
